DROP TABLE IF EXISTS USER CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS FUNDING CASCADE;

CREATE TABLE USER (
                    USER_ID bigint generated by default as identity,
                    NAME varchar(255),
                    primary key (USER_ID)
);

CREATE TABLE PRODUCT (
                         PRODUCT_ID bigint generated by default as identity,
                         TITLE varchar(255),
                         TARGET_FUNDING_AMOUNT integer,
                         START_DATE timestamp,
                         FINISH_DATE timestamp,
                         TOTAL_FUNDING_AMOUNT integer,
                         FUNDING_STATUS varchar(30),
                         FUNDING_USER_NUMBER integer,
                         VERSION integer,
                         primary key (PRODUCT_ID)
);

CREATE TABLE FUNDING (
                         FUNDING_ID bigint generated by default as identity,
                         FUNDING_AMOUNT integer,
                         FUNDING_DATE timestamp,
                         PRODUCT_ID bigint,
                         USER_ID bigint,
                         primary key(FUNDING_ID),
                         CONSTRAINT FK_FUNDING_TO_USER FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
                         CONSTRAINT FK_FUNDING_TO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)

);


